### PR TITLE
Discussion board for working around #110

### PR DESCRIPTION
**Pull request by 130s**
DO NOT MERGE.
This PR is intended for discussion ONLY. This should not be merged.
Workaround for #110.

Text format is out of scope of the discussion - once this reaches consensus, maintainer of answers.ros.org can update the web site accordingly.

@tfoote @gavanderhoorn

### CODE REVIEW

**Comment by gavanderhoorn** [comment]
Frustration is rising again, let's get back to this.

@130s: using a command line like that is a good idea. Not sure about `roswtf` though. That would be a lot of output pasted into questions, especially if we are going to ask this to be included in _all_ questions.

Quoting myself in https://github.com/ros-infrastructure/answers.ros.org/issues/110#issuecomment-139198092:

> [..] make info on ROS version, how it was installed, OS and OS version, cpu architecture, etc also 'mandatory'.

`lsb_release -a` is a good one, but will only work on systems that have `lsb_release`. I don't know of a truly cross-distro way of getting that info, so perhaps `lsb_release` is good enough for now. `cat /etc/*-release` seems like an option. For (barely) working ROS installs, running `os_detect.py` could also work.

`env | grep -i ros` would get us the ROS distro, but not how it was installed. I don't think we can (robustly) derive that from something, right?

`lspcu` gets us the arch, but what about `uname -p`? A bit more concise (1 vs 22 lines), and works without any additional tools.

**Comment by 130s** [comment]
Yeah, command of the choice is one question. For that, actually I have an input. 
Because it's been so much needed for my customers, and since there's already `roswtf` I thought it's the best to enhance it, I made a preliminary PR https://github.com/ros/ros_comm/pull/757 against roswtf package (not yet integrated with the roswtf command). This, as it is, works great for us already (asking users to download by `wget` or `curl`). There you see a lot of commands (ROS & sh) used. Apparently lots of caveats: users need to send a generated tarball that can be another hurdle or at least not the easiest, only works on Ubuntu so not the best for ROS2.0 era, etc. With this experience I have in mind:
- Write in cross-platform language, maybe in Python (as current `roswtf`. Definitely not in sh.
- I really want to add an option, only as an option though, to send the all captured log to web server where the tarball and all other info are unloaded to web page, provide unique link. Usecase will look something like below, so that users, even beginners, can easily run the diagnosis, paste the link on whichever forum:
  
  ```
    $ roswtf --public
  
    (Summarized output printed here)
  
    Detailed output is published at http://XXXXXX
  ```

Maybe my project during vacation if no one will work on this.

**Comment by tfoote** [comment]
An upload to gist or pastebin might be an interesting approach.

**Comment by tfoote** [comment]
The question prompt is now excerpting the Support Guidelines. If we have new/improved commands to add to the guidelines we can reexcerpt them into the question prompt.

**Comment by tfoote** [comment]
#110 is resolved with mandatory tags

**Pull request closed without merging**
